[package]
name = "toucan-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toucan-auth = { path = "../toucan-auth" }
toucan-config = { path = "../toucan-config" }
toucan-player = { path = "../toucan-player" }
toucan-protocol = { path = "../toucan-protocol" }
toucan-registry = { path = "../toucan-registry" }
toucan-world = { path = "../toucan-world" }
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
